version: '3.9'
services:
  jus-brasil-crawler:
    container_name: jus-brasil-crawler
    image: nettojulio/jus-brasil-crawler:latest
    environment:
      PORT: 3000
      BASE_URL_TJAL_FIRST_SEARCH: 'https://www2.tjal.jus.br/cpopg/show.do'
      BASE_URL_TJAL_SECOND_SEARCH: 'https://www2.tjal.jus.br/cposg5/show.do'
      BASE_URL_TJAL_SEARCH: 'https://www2.tjal.jus.br/cposg5/search.do'
      BASE_URL_TJCE_FIRST_SEARCH: 'https://esaj.tjce.jus.br/cpopg/show.do'
      BASE_URL_TJCE_SECOND_SEARCH: 'https://esaj.tjce.jus.br/cposg5/show.do'
      BASE_URL_TJCE_SEARCH: 'https://esaj.tjce.jus.br/cposg5/search.do'
      GATEWAY_URL: 'http://jus-brasil-gateway:8080/'
      SWAGGER_DOC_ENV: 'development'
    ports:
      - '3000:3000'
    restart: on-failure
    depends_on:
      - jus-brasil-gateway
    networks:
      - app-private-network

  jus-brasil-gateway:
    container_name: jus-brasil-gateway
    image: nettojulio/jus-brasil-gateway:latest
    ports:
      - '8080:8080'
    restart: on-failure
    networks:
      - app-private-network

networks:
  app-private-network:
    driver: bridge
    name: app-private-network
